cc_binary(
    name = "State",
    srcs = [
        "main.cpp",
        "TrafficLight.cpp",
        "TrafficLight.h",
        "states/Green.cpp",
        "states/Green.h",
        "states/Red.cpp",
        "states/Red.h",
        "states/State.cpp",
        "states/State.h",
        "states/Yellow.cpp",
        "states/Yellow.h",
    ],
)
