cc_binary(
    name = "Prototype",
    srcs = [
        "FerrariPrototype.cpp",
        "FerrariPrototype.h",
        "main.cpp",
        "PirelliFerrari.cpp",
        "PirelliFerrari.h",
        "Prototype.cpp",
        "Prototype.h",
    ],
)
