cc_binary(
    name = "Bridge",
    srcs = [
        "main.cpp",
        "include/Axle.h",
        "include/CarAxle.h",
        "include/Gamepad.h",
        "include/PlaneAxle.h",
        "include/PlaneWheel.h",
        "include/SteeringWheel.h",
        "axles/Axle.cpp",
        "axles/CarAxle.cpp",
        "axles/PlaneAxle.cpp",
        "wheels/Gamepad.cpp",
        "wheels/PlaneWheel.cpp",
        "wheels/SteeringWheel.cpp",
    ],
    copts = ["-IBridge/cpp-source/include"],
)
