cc_binary(
    name = "Memento",
    srcs = [
        "Caretaker.cpp",
        "Caretaker.h",
        "main.cpp",
        "Memento.cpp",
        "Memento.h",
        "Originator.cpp",
        "Originator.h",
        "PasswordMemento.cpp",
        "PasswordMemento.h",
    ],
)
