cc_binary(
    name = "Strategy",
    srcs = [
        "Duck.cpp",

        "Duck.h",
        "DuckHuntFlyBehaviour.cpp",
        "DuckHuntFlyBehaviour.h",
        "FlyBehaviour.cpp",
        "FlyBehaviour.h",
        "main.cpp",
        "QuackBehaviour.cpp",
        "QuackBehaviour.h",
        "SimpleFlyBehaviour.cpp",
        "SimpleFlyBehaviour.h",
        "SimpleQuackBehaviour.cpp",
        "SimpleQuackBehaviour.h",
        "SimpleSwimBehaviour.cpp",
        "SimpleSwimBehaviour.h",
        "SwimBehaviour.cpp",
        "SwimBehaviour.h",
    ],
)
