cc_binary(
    name = "ChainResponsibility",
    srcs = [
        "BaseHandler.h",
        "DivisionZeroHandler.h",
        "FileHandler.h",
        "LoggingHandler.h",
        "LogLevel.h",
        "StderrHandler.h",
        "main.cpp",
        "LogLevel.cpp",
        "LoggingHandler.cpp",
        "BaseHandler.cpp",
        "DivisionZeroHandler.cpp",
        "FileHandler.cpp",
        "StderrHandler.cpp",
    ],
)
