cc_binary(
    name = "Composite",
    srcs = [
        "include/Breakfast.h",
        "include/Dish.h",
        "include/DishComponent.h",
        "include/Milk.h",
        "main.cpp",
        "ration/DishComponent.cpp",
        "ration/Dish.cpp",
        "ration/Milk.cpp",
        "ration/Breakfast.cpp",
    ],
    copts = ["-IComposite/cpp-source/ration", "-IComposite/cpp-source/include"],
)
