cc_binary(
    name = "FactoryMethod",
    srcs = [
        "main.cpp",
        "routes/Route.cpp",
        "routes/Route.h",
        "routes/EthernetRoute.cpp",
        "routes/EthernetRoute.h",
        "routes/WifiRoute.cpp",
        "routes/WifiRoute.h",
        "routers/Router.cpp",
        "routers/Router.h",
        "routers/Hub.cpp",
        "routers/Hub.h",
        "routers/WifiRouter.cpp",
        "routers/WifiRouter.h",
    ],
    copts = [
    "-IFactoryMethod/cpp-source/routes",
    "-IFactoryMethod/cpp-source"],
)
